# dataset
load_col:
    inter: [review_id, user_id, item_id, rating, useful, funny, cool, timestamp]
    item: ['item_id','item_name','address','city','state','postal_code','latitude','longitude','item_stars','item_review_count','is_open','categories']
MAX_ITEM_LIST_LENGTH: 50
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

# Filtering
val_interval: {'timestamp': "[1546264800,1577714400]"}
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"
train_neg_sample_args: ~

# Model
n_layers: 4
n_heads: 8
hidden_size: 256
attribute_hidden_size: [64]
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.3
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
selected_features: ['categories']
pooling_mode: 'sum'
loss_type: 'CE'
weight_sharing: 'not'
fusion_type: 'gate'
lamdas: [10]
attribute_predictor: 'linear'
